---
title: "DOHMH Childcare Center Inspections"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
---

<style type="text/css">

h1.title {
  font-size: 38px;
  color: Black;
  text-align: center;
}
</style>

## Introduction

High-quality childcare is important for children safety and health. In our project , we did some data visualization with the NYC restaurant inspection dataset. We find this very inspiring and the idea of analyzing child care center inspections’ data came to our mind. A violation in a health care center would be, to some extent, more serious than violation in the restaurant and we would consider our project as a meaningful and realistic topic. We aim to find out some possible variables that would influence the rate of violation in child care centers in NYC.

## Website Overview

In our website, we have six parts in total.

In visualization part, we have:

* Violation Rate Distribution

1. Violation rate distribution by program type

2. Violation rate distribution by borough

* Violation Frequency

1. Number of violations by program type

2.  Number of violations by violation category

In statistical analysis part, we have:

* ANOVA test

* Chi-square test

* Proportion test

In shiny dashboard part, we have:

Dashboard related to maximum capacity, educational worker ratio and violation rate for different program types.

Click on [here](https://zuoqiaocui.shinyapps.io/shiny_violation/) to have a look

In model regression part, we have:

* Linear model

* Logistic model

In interactive map part, we have:

Maps that can show the violation rate in different zip code areas.

Click on [here](interactive_map.html) to learn more details.

In project report part, you can overview our final project report:

[Final project report](interactive_map.html)

## Dataset

In this project, the dataset we used is [here](https://data.cityofnewyork.us/Health/DOHMH-Childcare-Center-Inspections/dsg6-ifza), which is obtained from [NYC OpenData](https://opendata.cityofnewyork.us/)

This dataset contains a list of all inspections conducted and any associated violations at active, city-regulated,

center-based child care programs and summer camps over the past 3 years. The violations are pre-adjudicated.

Violations that are subject to potential penalties (fines) are submitted to NYC Office of Administrative Trials and

Hearing where they are adjudicated as either sustained/upheld or dismissed. The dataset also contains additional

information on the programs, including license information. For more information on child care in NYC visit:

https://www1.nyc.gov/site/doh/services/child-care.page.

## Screencast


## Group Members

Han Bao (hb2699)

Jasmine Niu (jn2855)

Qing Zhou (qz2266)

Zuoqiao Cui (zc2610)

Yuhuan Lin (yl5221)