<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />



<meta name="date" content="2022-12-08" />

<title>linear</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="rate_borough_viz.html">Violation Rate Distribution</a>
    </li>
    <li>
      <a href="model2.html">Model 2</a>
    </li>
  </ul>
</li>
<li>
  <a href="http://github.com/finijas01/">Statistical analysis</a>
</li>
<li>
  <a href="https://zuoqiaocui.shinyapps.io/shiny_violation/">Shiny Dashboard</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Model Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="model1.html">Model 1</a>
    </li>
    <li>
      <a href="model2.html">Model 2</a>
    </li>
  </ul>
</li>
<li>
  <a href="http://github.com/finijas01/">Project Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="http://github.com/finijas01/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">linear</h1>
<h4 class="date">2022-12-08</h4>

</div>


<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 4.2.2</code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
## ✔ ggplot2 3.4.0      ✔ purrr   0.3.5 
## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
## ✔ tidyr   1.2.1      ✔ stringr 1.5.0 
## ✔ readr   2.1.3      ✔ forcats 0.5.2</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Warning: package &#39;readr&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 4.2.2</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(dplyr)
library(rvest)</code></pre>
<pre><code>## 
## Attaching package: &#39;rvest&#39;
## 
## The following object is masked from &#39;package:readr&#39;:
## 
##     guess_encoding</code></pre>
<pre class="r"><code>library(purrr)
library(ggplot2)
library(modelr)</code></pre>
<pre><code>## Warning: package &#39;modelr&#39; was built under R version 4.2.2</code></pre>
<pre class="r"><code>library(mgcv)</code></pre>
<pre><code>## Warning: package &#39;mgcv&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## Warning: package &#39;nlme&#39; was built under R version 4.2.2</code></pre>
<pre><code>## 
## Attaching package: &#39;nlme&#39;
## 
## The following object is masked from &#39;package:dplyr&#39;:
## 
##     collapse
## 
## This is mgcv 1.8-41. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<pre class="r"><code>library(patchwork)
library(viridis)</code></pre>
<pre><code>## Loading required package: viridisLite</code></pre>
<pre class="r"><code>library(fastDummies)</code></pre>
<pre><code>## Warning: package &#39;fastDummies&#39; was built under R version 4.2.2</code></pre>
<pre class="r"><code>set.seed(1)</code></pre>
<div id="linear-regression-model" class="section level3">
<h3>Linear regression model</h3>
<p><em>Model selection:</em></p>
<p>To explore the possible predictors contributing to the
center-specific violation rate under each program type, we built a
linear regression model. In this model, we focused on the violation rate
and properties of each individual center.</p>
<p>To start with, we created a new variable named “rate”, which
represents the violation rate for each center, by using violation
category column. Here, rate = number of total violation for each center
and program / number of total inspection for each center and program,
during the past 3 year. This variable was used as the outcome of the
linear regression.</p>
<pre><code>## Rows: 26280 Columns: 34
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (22): Center Name, Legal Name, Building, Street, Borough, Phone, Permit ...
## dbl (11): ZipCode, Permit Number, Building Identification Number, Violation ...
## num  (1): Maximum Capacity
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>Next, we selected several variables closely related to the properties
of each center, as the potential predictors. After a thorough literature
review, we chose variables based on a hypothesized structure for the
factors underlying violation rate.</p>
<p>Linear model 1:</p>
<p>First, we fit a full model using program type, borough, status,
educational worker ratio of center-specific distinct records.</p>
<pre class="r"><code># select distinct records and related variables of each center
center_distinct_df = center_specific_df %&gt;%
  select(center_name, program_type, borough, status, maximum_capacity, total_educational_workers, educational_worker_ratio, rate)

# fit the full model
full_lm = center_distinct_df %&gt;%
 lm(rate ~ program_type + borough + status + educational_worker_ratio, data = .) 

full_lm %&gt;% 
  broom::tidy() %&gt;%
  knitr::kable(digit = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.865</td>
<td align="right">0.015</td>
<td align="right">57.405</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">program_typeinfant toddler</td>
<td align="right">-0.028</td>
<td align="right">0.011</td>
<td align="right">-2.425</td>
<td align="right">0.015</td>
</tr>
<tr class="odd">
<td align="left">program_typepreschool</td>
<td align="right">-0.004</td>
<td align="right">0.009</td>
<td align="right">-0.446</td>
<td align="right">0.656</td>
</tr>
<tr class="even">
<td align="left">boroughBROOKLYN</td>
<td align="right">-0.245</td>
<td align="right">0.006</td>
<td align="right">-42.837</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">boroughMANHATTAN</td>
<td align="right">-0.186</td>
<td align="right">0.006</td>
<td align="right">-30.364</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">boroughQUEENS</td>
<td align="right">-0.104</td>
<td align="right">0.006</td>
<td align="right">-17.314</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">boroughSTATEN ISLAND</td>
<td align="right">-0.323</td>
<td align="right">0.010</td>
<td align="right">-32.284</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">statusExpired-In Renewal</td>
<td align="right">-0.190</td>
<td align="right">0.012</td>
<td align="right">-15.804</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">statusPermitted</td>
<td align="right">-0.239</td>
<td align="right">0.011</td>
<td align="right">-21.128</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">educational_worker_ratio</td>
<td align="right">-0.083</td>
<td align="right">0.015</td>
<td align="right">-5.342</td>
<td align="right">0.000</td>
</tr>
</tbody>
</table>
<p>Linear model 2:</p>
<p>Second, we also proposed an alternative model by using
maximum_capacity, total educational workers and their interaction term
as the predictors, instead of the educational worker ratio.</p>
<pre class="r"><code># fit an alternative model
alt_lm = center_distinct_df %&gt;%
 lm(rate ~ program_type + borough + status + maximum_capacity * total_educational_workers, data = .) 

alt_lm %&gt;% 
  broom::tidy() %&gt;%
  knitr::kable(digit = 3)</code></pre>
<table>
<colgroup>
<col width="53%" />
<col width="11%" />
<col width="12%" />
<col width="12%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.842</td>
<td align="right">0.017</td>
<td align="right">51.008</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">program_typeinfant toddler</td>
<td align="right">-0.041</td>
<td align="right">0.012</td>
<td align="right">-3.432</td>
<td align="right">0.001</td>
</tr>
<tr class="odd">
<td align="left">program_typepreschool</td>
<td align="right">-0.006</td>
<td align="right">0.011</td>
<td align="right">-0.558</td>
<td align="right">0.577</td>
</tr>
<tr class="even">
<td align="left">boroughBROOKLYN</td>
<td align="right">-0.248</td>
<td align="right">0.006</td>
<td align="right">-43.482</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">boroughMANHATTAN</td>
<td align="right">-0.187</td>
<td align="right">0.006</td>
<td align="right">-30.447</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">boroughQUEENS</td>
<td align="right">-0.106</td>
<td align="right">0.006</td>
<td align="right">-17.709</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">boroughSTATEN ISLAND</td>
<td align="right">-0.329</td>
<td align="right">0.010</td>
<td align="right">-32.970</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">statusExpired-In Renewal</td>
<td align="right">-0.182</td>
<td align="right">0.012</td>
<td align="right">-15.258</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">statusPermitted</td>
<td align="right">-0.231</td>
<td align="right">0.011</td>
<td align="right">-20.568</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">maximum_capacity</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">2.558</td>
<td align="right">0.011</td>
</tr>
<tr class="odd">
<td align="left">total_educational_workers</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">0.191</td>
<td align="right">0.849</td>
</tr>
<tr class="even">
<td align="left">maximum_capacity:total_educational_workers</td>
<td align="right">0.000</td>
<td align="right">0.000</td>
<td align="right">-0.648</td>
<td align="right">0.517</td>
</tr>
</tbody>
</table>
<p>After comparing these two models, we decided to keep full_lm model,
due to its better goodness of fit and lower correlation among
variables.</p>
<pre class="r"><code># assess multicollinearity by vif
library(performance) </code></pre>
<pre><code>## Warning: package &#39;performance&#39; was built under R version 4.2.2</code></pre>
<pre><code>## 
## Attaching package: &#39;performance&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:modelr&#39;:
## 
##     mae, mse, rmse</code></pre>
<pre class="r"><code>check_collinearity(full_lm) # low correlation</code></pre>
<pre><code>## # Check for Multicollinearity
## 
## Low Correlation
## 
##                      Term  VIF   VIF 95% CI Increased SE Tolerance
##              program_type 1.78 [1.74, 1.82]         1.33      0.56
##                   borough 1.12 [1.10, 1.14]         1.06      0.89
##                    status 1.37 [1.35, 1.40]         1.17      0.73
##  educational_worker_ratio 1.46 [1.43, 1.49]         1.21      0.69
##  Tolerance 95% CI
##      [0.55, 0.58]
##      [0.88, 0.91]
##      [0.71, 0.74]
##      [0.67, 0.70]</code></pre>
<pre class="r"><code>check_collinearity(alt_lm)  # moderate correlation</code></pre>
<pre><code>## # Check for Multicollinearity
## 
## Low Correlation
## 
##              Term  VIF   VIF 95% CI Increased SE Tolerance Tolerance 95% CI
##      program_type 1.95 [1.90, 1.99]         1.39      0.51     [0.50, 0.53]
##           borough 1.12 [1.11, 1.14]         1.06      0.89     [0.87, 0.90]
##            status 1.36 [1.34, 1.39]         1.17      0.73     [0.72, 0.75]
##  maximum_capacity 1.70 [1.66, 1.73]         1.30      0.59     [0.58, 0.60]
## 
## Moderate Correlation
## 
##                                        Term  VIF   VIF 95% CI Increased SE
##                   total_educational_workers 5.95 [5.78, 6.11]         2.44
##  maximum_capacity:total_educational_workers 6.09 [5.92, 6.26]         2.47
##  Tolerance Tolerance 95% CI
##       0.17     [0.16, 0.17]
##       0.16     [0.16, 0.17]</code></pre>
<p><em>Model diagnostics:</em></p>
<p>We checked the assumptions of the residuals by using 4 plots as
follows. We found:</p>
<ol style="list-style-type: decimal">
<li><p>Linearity and homoscedasticity: from the Residuals vs Fitted
plot, we can see residuals form a horizontal ‘band’ around zero and its
value evenly dispersed around this reference line, suggesting the
variance of our residuals should be constant across all fitted
values.</p></li>
<li><p>Normality: from the Normal QQ plot, we can see a straight line
with small departures if we don’t consider cases 12349 and 12318,
suggesting the residuals follows a normal distribution.</p></li>
<li><p>Equal variance: again, from the Scale_Location plot, we can see a
horizontal line with roughly equally spread points, suggesting the
residuals are spread equally along the range of the predictors.</p></li>
<li><p>Outliers: from the Residuals vs Leverage plot, we can see no case
is outside of the dashed line of Cook’s distance 0.5, suggesting no
influential observations.</p></li>
</ol>
<pre class="r"><code># model diagnostics: Residuals vs Fitted plot, QQ plot, Scale_location, Residuals vs Leverage
plot(full_lm)</code></pre>
<p><img src="linear_files/figure-html/unnamed-chunk-8-1.png" width="672" /><img src="linear_files/figure-html/unnamed-chunk-8-2.png" width="672" /><img src="linear_files/figure-html/unnamed-chunk-8-3.png" width="672" /><img src="linear_files/figure-html/unnamed-chunk-8-4.png" width="672" /></p>
<p><em>Remedy:</em></p>
<p>Therefore, to address the slight model violation issue, we firstly
tried transformation to makes the data more ‘normal’. From the boxplot
of two numerical variables rate and educational worker ratio we can see
the latter is right skewed.</p>
<p>Since there are 0 value in these variables, log-transformation is not
applicable. Then we did square root transformation to the variable
educational_worker_ratio. However, this step didn’t significantly
improved the model.So we decided to go without transformation.</p>
<pre class="r"><code># Boxblot to check the initial distribution of outcome and key predictor
center_distinct_df  %&gt;%
par(mfrow = c(1,2))</code></pre>
<pre><code>## Warning in par(., mfrow = c(1, 2)): argument 1 does not name a graphical
## parameter</code></pre>
<pre class="r"><code>boxplot(center_distinct_df$educational_worker_ratio, main = &quot;Edu-worker Ratio&quot;)
boxplot(center_distinct_df$rate, main = &quot;Violation Rate&quot;)</code></pre>
<p><img src="linear_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code># Square root transformation
full_lm_sqrt = center_distinct_df %&gt;%
  lm(rate ~ program_type + borough + status + sqrt(educational_worker_ratio), data = .)</code></pre>
<p>In addition, although there is no influential points, case 12349 and
12318 affect the regression assumption as shown repeatedly.So we tried
to fit a new model named full_lm_out by removing these two cases. This
model works better then full_lm due to its increased adjusted
R-square.</p>
<pre class="r"><code># exclude two influential records
out_df = center_distinct_df[-c(12349, 12318),]

# fit model without influential points
full_lm_out = lm(rate ~ program_type + borough + status + educational_worker_ratio, data = out_df)

full_lm_out %&gt;% 
  broom::tidy() %&gt;%
  knitr::kable(digit = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">0.868</td>
<td align="right">0.015</td>
<td align="right">57.576</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">program_typeinfant toddler</td>
<td align="right">-0.027</td>
<td align="right">0.011</td>
<td align="right">-2.378</td>
<td align="right">0.017</td>
</tr>
<tr class="odd">
<td align="left">program_typepreschool</td>
<td align="right">-0.004</td>
<td align="right">0.009</td>
<td align="right">-0.417</td>
<td align="right">0.676</td>
</tr>
<tr class="even">
<td align="left">boroughBROOKLYN</td>
<td align="right">-0.245</td>
<td align="right">0.006</td>
<td align="right">-42.853</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">boroughMANHATTAN</td>
<td align="right">-0.186</td>
<td align="right">0.006</td>
<td align="right">-30.387</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">boroughQUEENS</td>
<td align="right">-0.103</td>
<td align="right">0.006</td>
<td align="right">-17.263</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">boroughSTATEN ISLAND</td>
<td align="right">-0.323</td>
<td align="right">0.010</td>
<td align="right">-32.289</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">statusExpired-In Renewal</td>
<td align="right">-0.193</td>
<td align="right">0.012</td>
<td align="right">-16.042</td>
<td align="right">0.000</td>
</tr>
<tr class="odd">
<td align="left">statusPermitted</td>
<td align="right">-0.242</td>
<td align="right">0.011</td>
<td align="right">-21.376</td>
<td align="right">0.000</td>
</tr>
<tr class="even">
<td align="left">educational_worker_ratio</td>
<td align="right">-0.084</td>
<td align="right">0.015</td>
<td align="right">-5.432</td>
<td align="right">0.000</td>
</tr>
</tbody>
</table>
<pre class="r"><code># model diagnostics: Residuals vs Fitted plot, QQ plot, Scale_location, Residuals vs Leverage
plot(full_lm_out)</code></pre>
<p><img src="linear_files/figure-html/unnamed-chunk-10-1.png" width="672" /><img src="linear_files/figure-html/unnamed-chunk-10-2.png" width="672" /><img src="linear_files/figure-html/unnamed-chunk-10-3.png" width="672" /><img src="linear_files/figure-html/unnamed-chunk-10-4.png" width="672" /></p>
<p><em>Model validation:</em></p>
<p>We used 5-fold cross validation to test the model performance. Based
on a rule of thumb, RMSE values between 0.2 and 0.5 shows that the model
can relatively predict the data accurately. Thus our model boasts good
RMSE value(RMSE = 0.24), suggesting relatively good predictive
ability.</p>
<pre class="r"><code>library(caret)</code></pre>
<pre><code>## Warning: package &#39;caret&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## 
## Attaching package: &#39;caret&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:purrr&#39;:
## 
##     lift</code></pre>
<pre class="r"><code># Use 5-fold validation and create the training sets
train = trainControl(method = &quot;cv&quot;, number = 5)

model_caret = train(rate ~ program_type + borough + status + educational_worker_ratio,
                   data = out_df,
                   trControl = train,
                   method = &#39;lm&#39;,
                   na.action = na.pass)</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre><code>## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading

## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading

## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading

## Warning in predict.lm(modelFit, newdata): prediction from a rank-deficient fit
## may be misleading</code></pre>
<pre class="r"><code>model_caret$finalModel</code></pre>
<pre><code>## 
## Call:
## lm(formula = .outcome ~ ., data = dat)
## 
## Coefficients:
##                   (Intercept)   `program_typeinfant toddler`  
##                      0.867766                      -0.027051  
##         program_typepreschool  `program_typeschool age camp`  
##                     -0.003946                             NA  
##               boroughBROOKLYN               boroughMANHATTAN  
##                     -0.244722                      -0.186472  
##                 boroughQUEENS         `boroughSTATEN ISLAND`  
##                     -0.103485                      -0.323262  
##    `statusExpired-In Renewal`                statusPermitted  
##                     -0.192734                      -0.242073  
##      educational_worker_ratio  
##                     -0.083874</code></pre>
<pre class="r"><code>print(model_caret)</code></pre>
<pre><code>## Linear Regression 
## 
## 16449 samples
##     4 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (5 fold) 
## Summary of sample sizes: 13159, 13160, 13159, 13159, 13159 
## Resampling results:
## 
##   RMSE       Rsquared   MAE      
##   0.2431557  0.1565823  0.1982754
## 
## Tuning parameter &#39;intercept&#39; was held constant at a value of TRUE</code></pre>
<p><em>Conclusion:</em></p>
<p>We chose full_lm_out as our final linear model:</p>
<p>rate = 0.868 - 0.027(program_type_infant toddler) -
0.245(borough_BROOKLYN) -0.186(borough_MANHATTAN) -
0.103(borough_QUEENS) - 0.323(borough_STATEN ISLAND) -
0.193(status_Expired In Renewal) - 0.242(status_Permitted) -
0.084(educational_worker_ratio)</p>
<p>Interpretation:</p>
<p>In this model, the outcome is “rate”, indicating the violation rate
for each center based on different program type. Our key predictor is
the numeric variable of “educational_worker_ratio”, which is the
program-specific total number of educational worker in each center,
divided by the maximum capacity, based on the square footage of class
and play rooms, the number of toilets and sinks, and overall estimates
from the NYC Department of Buildings. As shown in the plot below, our
model suggests the value of the estimated mean violation rate decreases
by 0.084 for each unit increase in educational worker ratio, while
holding all other variables fixed.</p>
<p>We also included several categorical variables into our model. Based
on the output, the interpretations of coefficients estimates are as
follows:</p>
<p>The value of the estimated mean violation rate for centers located in
Brooklyn, Manhattan, Queens and Staten island are 0.245, 0.186, 0.103
and 0.323 less than centers located in Bronx, respectively, while
holding other variables constant.</p>
<p>The value of the estimated mean violation rate for centers with
licence status as expired in renewal and as permitted is 0.193 and 0.242
less than centers with licence status as active, while holding other
variables constant.</p>
<p>The value of the estimated mean violation rate for centers implement
infant toddler program is 0.028 less than centers implement all age camp
program, while holding other variables constant.</p>
<pre class="r"><code># Scatter plot with regression line overlaid and 95% confidence bands, between rate and our main predictor:educational worker ratio 
out_df %&gt;% 
  ggplot(aes(educational_worker_ratio, rate)) + geom_point(color = &#39;blue&#39;) + 
  theme_bw() +
  geom_smooth(method = &#39;lm&#39;, se = TRUE, color = &#39;red&#39;) +
  labs(x = &quot;educational worker ratio&quot;, y = &quot;Violation rate&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="linear_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
