<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Logistic Regression</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Visualization
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="rate_borough_viz.html">Violation Rate Distribution</a>
    </li>
    <li>
      <a href="violation_category_viz.html">Violation Frequency</a>
    </li>
  </ul>
</li>
<li>
  <a href="Statistical-analysis.html">Statistical analysis</a>
</li>
<li>
  <a href="https://zuoqiaocui.shinyapps.io/shiny_violation/">Shiny Dashboard</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Model Regression
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="linear.html">Linear Model</a>
    </li>
    <li>
      <a href="logistic.html">Logistic Model</a>
    </li>
  </ul>
</li>
<li>
  <a href="interactive_map.html">Interactive Map</a>
</li>
<li>
  <a href="report.html">Project Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="http://github.com/finijas01/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Logistic Regression</h1>

</div>


<pre class="r"><code>knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE)</code></pre>
<pre class="r"><code>library(tidyverse)
library(broom)
library(viridis)
library(purrr)
library(modelr)
theme_set(theme_classic())

child_data = read_csv(&quot;./data/DOHMH_Childcare_Center_Inspections.csv&quot;) %&gt;%
  janitor::clean_names() %&gt;%
  distinct()

child_data = child_data %&gt;% 
  select(center_name, borough, zip_code, status, age_range, maximum_capacity,program_type, facility_type, 
         child_care_type, violation_category,
         violation_status,violation_rate_percent:average_critical_violation_rate,regulation_summary,
         inspection_summary_result) %&gt;%
  drop_na(zip_code, age_range, violation_rate_percent,public_health_hazard_violation_rate, critical_violation_rate) %&gt;% 
  filter(maximum_capacity != 0) %&gt;% 
  mutate(
    educational_worker_ratio = total_educational_workers/maximum_capacity,
    program_type = tolower(program_type),
    facility_type = tolower(facility_type),
    borough =  as.factor(borough),
    status = as.factor(status),
    program_type = as.factor(program_type),
    facility_type = as.factor(facility_type),
    child_care_type = as.factor(child_care_type)
  )

#create binary variable according to regulation_summary
child_data &lt;- child_data %&gt;%
  mutate(violation = if_else(.$regulation_summary == &#39;There were no new violations observed at the time of this inspection/visit.&#39;,&#39;0&#39;,&#39;1&#39;),
         violation = as.factor(violation))</code></pre>
<p><br></p>
<div id="model-fit" class="section level2">
<h2><strong>Model fit</strong></h2>
<ul>
<li>We created a binary variable, violation, which represents the result
of every inspection. Then we fitted a logistic regression with log of
odds ratio of violation rate as the outcome and borough, program_type,
status and educational_worker_ratio as predictors, using every
observation as one case. Then we obtained the estimate and CI of the
adjusted odds ratio for having violation.</li>
</ul>
<p><br></p>
<div id="build-model" class="section level3">
<h3><em>- Build Model</em></h3>
<pre class="r"><code>model_log &lt;- glm(violation ~ borough + status  + program_type + educational_worker_ratio,data = child_data,family = binomial(link=logit))
model_log %&gt;%
  broom::tidy(conf.int = T) %&gt;% 
  mutate(OR = exp(estimate),
         CI_lower = exp(exp(conf.low)),
         CI_upper = exp(exp(conf.high)),
         p_val = rstatix::p_format(p.value, digits = 2)) %&gt;% 
  select(term, OR, CI_lower,CI_upper, p_val) %&gt;% 
  knitr::kable(digits = 3, align = &quot;lccc&quot;, 
               col.names = c(&quot;Term&quot;, &quot;Estimated adjusted OR&quot;, &quot;CI lower bound&quot;, &quot;CI upper bound&quot;, &quot;p-value&quot;))</code></pre>
<table>
<colgroup>
<col width="30%" />
<col width="25%" />
<col width="17%" />
<col width="17%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Term</th>
<th align="center">Estimated adjusted OR</th>
<th align="center">CI lower bound</th>
<th align="center">CI upper bound</th>
<th align="left">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="center">4.715</td>
<td align="center">38.429</td>
<td align="center">4.501930e+02</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">boroughBROOKLYN</td>
<td align="center">0.351</td>
<td align="center">1.376</td>
<td align="center">1.472000e+00</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="odd">
<td align="left">boroughMANHATTAN</td>
<td align="center">0.454</td>
<td align="center">1.506</td>
<td align="center">1.652000e+00</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">boroughQUEENS</td>
<td align="center">0.648</td>
<td align="center">1.798</td>
<td align="center">2.045000e+00</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="odd">
<td align="left">boroughSTATEN ISLAND</td>
<td align="center">0.247</td>
<td align="center">1.230</td>
<td align="center">1.342000e+00</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">statusExpired-In Renewal</td>
<td align="center">0.448</td>
<td align="center">1.438</td>
<td align="center">1.736000e+00</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="odd">
<td align="left">statusPermitted</td>
<td align="center">0.355</td>
<td align="center">1.337</td>
<td align="center">1.541000e+00</td>
<td align="left">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">program_typeinfant toddler</td>
<td align="center">0.908</td>
<td align="center">2.123</td>
<td align="center">2.992000e+00</td>
<td align="left">0.3159</td>
</tr>
<tr class="odd">
<td align="left">program_typepreschool</td>
<td align="center">1.001</td>
<td align="center">2.355</td>
<td align="center">3.218000e+00</td>
<td align="left">0.9944</td>
</tr>
<tr class="even">
<td align="left">program_typeschool age camp</td>
<td align="center">1.644</td>
<td align="center">1.164</td>
<td align="center">4.762402e+15</td>
<td align="left">0.6894</td>
</tr>
<tr class="odd">
<td align="left">educational_worker_ratio</td>
<td align="center">0.706</td>
<td align="center">1.721</td>
<td align="center">2.503000e+00</td>
<td align="left">0.0093</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Predict the probability (p) of violation positivity
probabilities &lt;- predict(model_log, type = &quot;response&quot;)
predicted.classes &lt;- ifelse(probabilities &gt; 0.5, &quot;pos&quot;, &quot;neg&quot;)
head(predicted.classes)</code></pre>
<pre><code>##     1     2     3     4     5     6 
## &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;neg&quot; &quot;pos&quot;</code></pre>
<pre class="r"><code>#probabilities</code></pre>
<p><br></p>
</div>
<div id="results-and-summary" class="section level3">
<h3><em>- Results and summary</em></h3>
<pre class="r"><code>summary(model_log)</code></pre>
<pre><code>## 
## Call:
## glm(formula = violation ~ borough + status + program_type + educational_worker_ratio, 
##     family = binomial(link = logit), data = child_data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.8520  -1.0508  -0.8782   1.1727   1.7934  
## 
## Coefficients:
##                               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                  1.5508044  0.1314607  11.797  &lt; 2e-16 ***
## boroughBROOKLYN             -1.0465054  0.0487599 -21.462  &lt; 2e-16 ***
## boroughMANHATTAN            -0.7905779  0.0518737 -15.240  &lt; 2e-16 ***
## boroughQUEENS               -0.4339075  0.0503992  -8.609  &lt; 2e-16 ***
## boroughSTATEN ISLAND        -1.3983570  0.0896874 -15.591  &lt; 2e-16 ***
## statusExpired-In Renewal    -0.8025015  0.1065993  -7.528 5.14e-14 ***
## statusPermitted             -1.0349521  0.1013003 -10.217  &lt; 2e-16 ***
## program_typeinfant toddler  -0.0960457  0.0957691  -1.003  0.31591    
## program_typepreschool        0.0005541  0.0792675   0.007  0.99442    
## program_typeschool age camp  0.4969849  1.2435739   0.400  0.68942    
## educational_worker_ratio    -0.3480415  0.1339063  -2.599  0.00935 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 22719  on 16453  degrees of freedom
## Residual deviance: 21933  on 16443  degrees of freedom
## AIC: 21955
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<ul>
<li>Conclusion:</li>
</ul>
<p>We can see from the summary that the licence status and educational
worker ratio of the child care centers are</p>
<p>significant predictors of the violation rate with p-value&lt; 0.05
while the facility type doesn’t significantly</p>
<p>influence the violation rate with p-value&gt;0.05.</p>
<p><br> <br></p>
</div>
</div>
<div id="visualization" class="section level2">
<h2><strong>Visualization</strong></h2>
<p><br></p>
<ul>
<li>Estimated OR with CI</li>
</ul>
<pre class="r"><code>#  Extract the adjusted odds ratio (and CI) for having violation comparing licence type of &quot;active&quot; against &quot;Expired-in renewal&quot; from all the boroughs.
all_logistic_E = child_data %&gt;% 
  nest(data = -borough) %&gt;% 
  mutate(
    models = map(data, ~glm(violation ~ status  +  program_type + educational_worker_ratio, data = ., family = binomial(link = &quot;logit&quot;))),
    results = map(models, ~broom::tidy(.x, conf.int = T))) %&gt;% 
  select(borough, results) %&gt;% 
  unnest(results) %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(conf.low),
    CI_upper = exp(conf.high),
    p_val = rstatix::p_format(p.value, digits = 2)
  ) %&gt;% 
  filter(term == &quot;statusExpired-In Renewal&quot;) %&gt;% 
  select(borough, OR, CI_lower,CI_upper, p_val) 
all_logistic_E %&gt;% 
  knitr::kable(digits = 3, align = &quot;llccc&quot;, col.names = c(&quot;Borough&quot;, &quot;Estimated adjusted OR&quot;, &quot;CI lower bound&quot;, &quot;CI upper bound&quot;, &quot;p-value&quot;))</code></pre>
<table>
<colgroup>
<col width="18%" />
<col width="28%" />
<col width="20%" />
<col width="20%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Borough</th>
<th align="left">Estimated adjusted OR</th>
<th align="center">CI lower bound</th>
<th align="center">CI upper bound</th>
<th align="center">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">BROOKLYN</td>
<td align="left">0.406</td>
<td align="center">0.265</td>
<td align="center">0.614</td>
<td align="center">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">BRONX</td>
<td align="left">0.357</td>
<td align="center">0.165</td>
<td align="center">0.708</td>
<td align="center">0.00519</td>
</tr>
<tr class="odd">
<td align="left">QUEENS</td>
<td align="left">0.644</td>
<td align="center">0.390</td>
<td align="center">1.057</td>
<td align="center">0.08323</td>
</tr>
<tr class="even">
<td align="left">MANHATTAN</td>
<td align="left">0.592</td>
<td align="center">0.413</td>
<td align="center">0.843</td>
<td align="center">0.00395</td>
</tr>
<tr class="odd">
<td align="left">STATEN ISLAND</td>
<td align="left">0.721</td>
<td align="center">0.235</td>
<td align="center">2.323</td>
<td align="center">0.56915</td>
</tr>
</tbody>
</table>
<pre class="r"><code>all_logistic_P = child_data %&gt;% 
  nest(data = -borough) %&gt;% 
  mutate(
    models = map(data, ~glm(violation ~ status  +  program_type + educational_worker_ratio, data = ., family = binomial(link = &quot;logit&quot;))),
    results = map(models, ~broom::tidy(.x, conf.int = T))) %&gt;% 
  select(borough, results) %&gt;% 
  unnest(results) %&gt;% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(conf.low),
    CI_upper = exp(conf.high),
    p_val = rstatix::p_format(p.value, digits = 2)
  ) %&gt;% 
  filter(term == &quot;statusPermitted&quot;) %&gt;% 
  select(borough, OR, CI_lower,CI_upper, p_val) 
all_logistic_P %&gt;% 
  knitr::kable(digits = 3, align = &quot;llccc&quot;, col.names = c(&quot;Borough&quot;, &quot;Estimated adjusted OR&quot;, &quot;CI lower bound&quot;, &quot;CI upper bound&quot;, &quot;p-value&quot;))</code></pre>
<table>
<colgroup>
<col width="18%" />
<col width="28%" />
<col width="20%" />
<col width="20%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Borough</th>
<th align="left">Estimated adjusted OR</th>
<th align="center">CI lower bound</th>
<th align="center">CI upper bound</th>
<th align="center">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">BROOKLYN</td>
<td align="left">0.314</td>
<td align="center">0.206</td>
<td align="center">0.470</td>
<td align="center">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">BRONX</td>
<td align="left">0.433</td>
<td align="center">0.204</td>
<td align="center">0.836</td>
<td align="center">0.01894</td>
</tr>
<tr class="odd">
<td align="left">QUEENS</td>
<td align="left">0.292</td>
<td align="center">0.198</td>
<td align="center">0.422</td>
<td align="center">&lt;0.0001</td>
</tr>
<tr class="even">
<td align="left">MANHATTAN</td>
<td align="left">0.454</td>
<td align="center">0.320</td>
<td align="center">0.640</td>
<td align="center">&lt;0.0001</td>
</tr>
<tr class="odd">
<td align="left">STATEN ISLAND</td>
<td align="left">0.478</td>
<td align="center">0.162</td>
<td align="center">1.485</td>
<td align="center">0.18184</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Create a plot showing the estimated ORs and CIs for each borough
all_logistic_E %&gt;% 
  mutate(borough = fct_reorder(borough, OR)) %&gt;%
  ggplot(aes(x = borough, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = &quot;Borough&quot;, y = &quot;Estimated OR with CI(expired)&quot;)</code></pre>
<p><img src="logistic_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>all_logistic_P %&gt;% 
  mutate(borough = fct_reorder(borough, OR)) %&gt;%
  ggplot(aes(x = borough, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = &quot;Borough&quot;, y = &quot;Estimated OR with CI(permitted)&quot;)</code></pre>
<p><img src="logistic_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<ul>
<li>Conclusion:</li>
</ul>
<p>From these two plots we can see that in Brooklyn, Bronx and
Manhattan, the 95% confidence interval of odds ratio doesn’t include 1
and this tells us that in these three regions, cases with licence status
of active generally have more violation probability than cases with
status of expired or in-renewal. Similarly, in Brooklyn, Bronx, Queens
and Manhattan, the 95% confidence interval of odds ratio doesn’t include
1 and this tells us that in these four regions, cases with licence
status of active generally have more violation probability than cases
with status of permitted.</p>
<p><br> <br></p>
</div>
<div id="model-diagnostics" class="section level2">
<h2><strong>Model diagnostics</strong></h2>
<ul>
<li>Remove categorical variables from the original data frame and bind
the logit values to the data</li>
</ul>
<pre class="r"><code>#select only numeric predictors
child_data &lt;- child_data %&gt;%
  dplyr::select(educational_worker_ratio) 
predictors &lt;- colnames(child_data)
child_data &lt;- child_data %&gt;%
  mutate(logit = log(probabilities/(1-probabilities))) %&gt;%
  gather(key = &quot;predictors&quot;, value = &quot;predictor.value&quot;, -logit)</code></pre>
<ul>
<li>Create the scatter plots:</li>
</ul>
<pre class="r"><code>ggplot(child_data, aes(logit, predictor.value))+
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = &quot;loess&quot;) + 
  theme_bw() + 
  facet_wrap(~predictors, scales = &quot;free_y&quot;)</code></pre>
<p><img src="logistic_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<ul>
<li>From this plot we can see that variable educational_worker_ratio is
quite linearly associated with the violation rate in logit scale.</li>
</ul>
<pre class="r"><code># Extract model results
model_log.data &lt;- augment(model_log) %&gt;% 
  mutate(index = 1:n()) 
ggplot(model_log.data, aes(index, .std.resid)) + 
  geom_point(aes(color = violation), alpha = .5) +
  theme_bw()</code></pre>
<p><img src="logistic_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<ul>
<li>Diagnostic Conclusion</li>
</ul>
<p>From the plot we can see that the standard deviation of the data are
all in acceptable region which means there’s no significant outliers in
the dataset.</p>
<p><br> <br></p>
</div>
<div id="model-interpretation" class="section level2">
<h2><strong>Model interpretation</strong></h2>
<p>In this model, the outcome is log odds ratio of violation. Our key
predictor is the numeric variable of “educational_worker_ratio”, which
is the program-specific total number of educational worker in each
center, divided by the maximum capacity, based on the square footage of
class and play rooms, the number of toilets and sinks, and overall
estimates from the NYC Department of Buildings. With the log of odds
ratio for the association between violation and educational_worker_ratio
= -0.34, holding other variables fixed, the odds of having the violation
will decrease by 29%, for one unit increase in educational worker
ratio.</p>
<p>We also included several categorical variables into our model. Based
on the output, the interpretations of coefficients estimates are as
follows: with log(odds ratio) = -1.04, -0.79, -0.33 and -1.40, the odds
of having violation in Brooklyn, Manhattan, Queens and Staten island is
0.35, 0.45, 0.65 and 0.24 times of that in Bronx. with log(odds ratio) =
-0.80 and -1.03, the odds of having violation in centers with
“expired-in renewal” and “permitted” license is 0.45 and 0.36 times of
that among centers with “active” license</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
